baseurl = "https://matrosov.netlify.com"
title = "Rootkits and Bootkits"

theme = "coder-portfolio"

DefaultContentLanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true


[params]
    author = "Rootkits and Bootkits"
    description = "Rootkits and Bootkits official book website"
    avatarurl = "images/avatar.jpg"

    hideCredits = false
    hideCopyright = false

    snsShare = true

    thumbnail = "images/avatar.jpg"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/bootkitsbook/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/rehints"
[[params.social]]
    name = "Publisher"
    weight = 3
    url = "https://nostarch.com/rootkits"
[[params.social]]
    name = "Amazon"
    weight = 3
    url = "https://www.amazon.com/Rootkits-Bootkits-Reversing-Malware-Generation/dp/1593277164"    

[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English" # The language name to be displayed in the selector.
        title = "by Alex Matrosov, Eugene Rodionov, and Sergey Bratus"

        # You can configure the theme parameter for each language.
        [languages.en.params]
            author = "Rootkits and Bootkits"
            info = "Reversing Modern Malware and Next Generation Threats"

        [languages.en.menu] # It is possible to change the menu too.

            [[languages.en.menu.main]]
                name = "About"
                weight = 1.0
                url = "about"

            [[languages.en.menu.main]]
                name = "Bibliography"
                weight = 2.0
                url = "https://github.com/bootkitsbook/bibliography"

            [[languages.en.menu.main]]
                name = "Blog"
                weight = 3
                url = "https://medium.com/@matrosov"
            [[languages.en.menu.main]]
                name = "Feedback"
                weight = 5
                url = "feedback"
